"""empty message

Revision ID: 47417c5092ce
Revises: dafd288ac1b4
Create Date: 2022-08-23 09:09:01.982879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47417c5092ce'
down_revision = 'dafd288ac1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorito', sa.Column('usuario_inicial_id', sa.Integer(), nullable=False))
    op.add_column('favorito', sa.Column('usuario_favorito_id', sa.Integer(), nullable=False))
    op.drop_constraint('favorito_usuario_favorito_fkey', 'favorito', type_='foreignkey')
    op.create_foreign_key(None, 'favorito', 'usuario', ['usuario_favorito_id'], ['id'])
    op.create_foreign_key(None, 'favorito', 'usuario', ['usuario_inicial_id'], ['id'])
    op.drop_column('favorito', 'usuario_favorito')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorito', sa.Column('usuario_favorito', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorito', type_='foreignkey')
    op.drop_constraint(None, 'favorito', type_='foreignkey')
    op.create_foreign_key('favorito_usuario_favorito_fkey', 'favorito', 'usuario', ['usuario_favorito'], ['id'])
    op.drop_column('favorito', 'usuario_favorito_id')
    op.drop_column('favorito', 'usuario_inicial_id')
    # ### end Alembic commands ###
