"""empty message

Revision ID: 549544cd4f99
Revises: 47417c5092ce
Create Date: 2022-08-30 10:07:48.250039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549544cd4f99'
down_revision = '47417c5092ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_creador_id', sa.Integer(), nullable=False),
    sa.Column('usuario_invitado_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_invitado_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitacion')
    # ### end Alembic commands ###
